### ISSUE TITLE
Set up CI/CD

### ISSUE THREAD

**Issue by govindkrjoshi** [nilenso/winter-onboarding-2021#14]
- Use github actions for CI/CD
- Use heroku for deployment

### Tasks
- [x] Run tests on every push
- [x] Create a build on every push and store it as an artifact
- [x] Setup test coverage checks
- [x] Setup linting and formatting checks
- [ ] When a PR is merged to main, deploy to staging
- [ ] Add a manual trigger to deploy to production
