### ISSUE TITLE
Setup the project

### ISSUE THREAD

**Issue by govindkrjoshi** [nilenso/winter-onboarding-2021#15]
#### Technology Stack
- Clojure
- Postgres
- Ring - http server
- Bidi - routing
- Aero - config management
- next-jdbc - database connection
- hiccup - html templates
- mount - app state management

### Tasks
- [x] Figure out the dependences
- [x] Local postgres db setup
- [x] Schema migrations
- [x] local setup
- [x] Health check endpoint
- [ ] Tests
- [x] [Reloaded](https://www.cognitect.com/blog/2013/06/04/clojure-workflow-reloaded) repl setup
